startCommand: PUPPETEER_CACHE_DIR=/tmp/puppeteer node server.js

services:
  - type: web
    name: hwaseonad
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_VERSION
        value: 18